#!/usr/bin/env python3
"""
hex_to_vhdl_rom.py - Generate VHDL ROM from Intel HEX file

Converts an Intel HEX file to a VHDL ROM component with explicit
array initialization. This avoids synthesis issues with file-based
ROM initialization in GHDL/Yosys.

Features:
- Explicit array initialization (avoids Yosys file-based ROM bugs)
- Includes ram_style="logic" attribute for synthesis control
- Works with GHDL + Yosys + nextpnr-ecp5 toolchain

Usage:
    python3 hex_to_vhdl_rom.py input.hex output.vhdl [--size SIZE] [--entity NAME]

Arguments:
    input.hex   - Intel HEX format input file
    output.vhdl - Output VHDL ROM file
    --size SIZE - ROM size in bytes (default: 4096)
    --entity NAME - Entity name (default: rom_program)
"""

import sys
import os
import argparse
from datetime import datetime


def parse_intel_hex(filename):
    """Parse Intel HEX file and return dict of address -> byte."""
    data = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or not line.startswith(':'):
                continue

            # Parse Intel HEX record
            byte_count = int(line[1:3], 16)
            address = int(line[3:7], 16)
            record_type = int(line[7:9], 16)

            if record_type == 0x00:  # Data record
                for i in range(byte_count):
                    byte_val = int(line[9 + i*2:11 + i*2], 16)
                    data[address + i] = byte_val
            elif record_type == 0x01:  # EOF record
                break

    return data


def generate_vhdl_rom(data, rom_size, entity_name, source_file, compat_mode=False):
    """Generate VHDL ROM source code with explicit initialization.

    Args:
        data: Dict of address -> byte
        rom_size: ROM size in bytes
        entity_name: VHDL entity name
        source_file: Source filename for comment
        compat_mode: If True, add ROM_FILE generic for compatibility with b8008_top
    """

    # Calculate address width
    addr_width = (rom_size - 1).bit_length()

    # Find actual data range
    if data:
        min_addr = min(data.keys())
        max_addr = max(data.keys())
        data_bytes = len(data)
    else:
        min_addr = max_addr = data_bytes = 0

    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Generic declaration for compatibility mode
    if compat_mode:
        generic_decl = '''    generic (
        -- Ignored - ROM data is baked in at build time
        ROM_FILE : string := ""
    );
'''
    else:
        generic_decl = ''

    vhdl = f"""--------------------------------------------------------------------------------
-- {entity_name}.vhdl - Auto-generated ROM
--------------------------------------------------------------------------------
-- Generated: {timestamp}
-- Source: {source_file}
-- Size: {rom_size} bytes ({rom_size // 1024}KB)
-- Data: {data_bytes} bytes (0x{min_addr:04X} - 0x{max_addr:04X})
--
-- This file is auto-generated by hex_to_vhdl_rom.py
-- DO NOT EDIT MANUALLY - changes will be overwritten
--
-- Uses explicit array initialization to avoid Yosys synthesis bugs
-- that occur with file-based ROM initialization.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity {entity_name} is
{generic_decl}    port (
        ADDR     : in  std_logic_vector({addr_width - 1} downto 0);
        DATA_OUT : out std_logic_vector(7 downto 0);
        CS_N     : in  std_logic
    );
end entity {entity_name};

architecture rtl of {entity_name} is
    type rom_array is array(0 to {rom_size - 1}) of std_logic_vector(7 downto 0);

    -- Synthesis attribute to control ROM implementation
    -- "logic" forces LUT-based implementation (no block RAM)
    attribute ram_style : string;

    constant ROM : rom_array := (
"""

    # Generate ROM initialization - group by 8 bytes per line for readability
    lines = []
    for addr in range(rom_size):
        byte_val = data.get(addr, 0x00)  # Default to 0x00 for unused locations

        if addr % 8 == 0:
            if addr > 0:
                lines.append("")  # Start new line
            lines.append(f"        -- 0x{addr:04X}")
            lines.append("        ")

        # Add byte with proper formatting
        if addr == rom_size - 1:
            lines[-1] += f'x"{byte_val:02X}"'  # Last byte, no comma
        else:
            lines[-1] += f'x"{byte_val:02X}", '

    vhdl += "\n".join(lines)

    vhdl += f"""
    );

    -- Apply ram_style attribute to ROM constant
    attribute ram_style of ROM : constant is "logic";

begin
    -- Asynchronous ROM read
    DATA_OUT <= ROM(to_integer(unsigned(ADDR)));

end architecture rtl;
"""

    return vhdl


def main():
    parser = argparse.ArgumentParser(
        description='Convert Intel HEX to VHDL ROM with explicit initialization'
    )
    parser.add_argument('input_hex', help='Input Intel HEX file')
    parser.add_argument('output_vhdl', help='Output VHDL file')
    parser.add_argument('--size', type=int, default=4096,
                        help='ROM size in bytes (default: 4096)')
    parser.add_argument('--entity', default='rom_4kx8',
                        help='Entity name (default: rom_4kx8)')
    parser.add_argument('--compat', action='store_true',
                        help='Add ROM_FILE generic for b8008_top compatibility')

    args = parser.parse_args()

    # Parse input file
    if not os.path.exists(args.input_hex):
        print(f"Error: Input file not found: {args.input_hex}", file=sys.stderr)
        sys.exit(1)

    data = parse_intel_hex(args.input_hex)

    if not data:
        print(f"Warning: No data found in {args.input_hex}", file=sys.stderr)

    # Generate VHDL
    vhdl = generate_vhdl_rom(data, args.size, args.entity,
                             os.path.basename(args.input_hex),
                             compat_mode=args.compat)

    # Write output
    with open(args.output_vhdl, 'w') as f:
        f.write(vhdl)

    # Print summary
    min_addr = min(data.keys()) if data else 0
    max_addr = max(data.keys()) if data else 0
    print(f"Generated {args.output_vhdl}")
    print(f"  Entity: {args.entity}")
    print(f"  ROM size: {args.size} bytes")
    print(f"  Data: {len(data)} bytes (0x{min_addr:04X} - 0x{max_addr:04X})")


if __name__ == '__main__':
    main()
