; GENERATED by gen_cond_matrix.py - do not edit by hand.
; All 48 conditional combos (VPLAN XP-08); expectations in
; cond_matrix_expected.txt consumed by check_cond_matrix_test.sh.
;
; D counts taken calls, E counts not-taken returns (helper falls
; through the RXc). FAIL emits checkpoint 0xFE and halts.

        cpu     8008new
        page    0

CHKPT   equ     31

        org     0000h
STARTUP:
        MOV     A,A
        MOV     A,A
        JMP     MAIN

SUBR:                           ; taken-call counter
        INR     D
        RET

H_RC:
        RC                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RNC:
        RNC                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RZ:
        RZ                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RNZ:
        RNZ                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RM:
        RM                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RP:
        RP                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RPE:
        RPE                      ; conditional return under test
        INR     E               ; not-taken path
        RET

H_RPO:
        RPO                      ; conditional return under test
        INR     E               ; not-taken path
        RET

        org     0200h
MAIN:
        MVI     D,00h
        MVI     E,00h

; combo 1: J C=1 sense=T -> taken
        MVI     A,0FFh
        ADI     01h
        JC      L1
        JMP     FAIL
L1:
        MVI     A,01
        OUT     CHKPT

; combo 2: J C=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        JC      FAIL
        MVI     A,02
        OUT     CHKPT

; combo 3: J C=1 sense=F -> not taken
        MVI     A,0FFh
        ADI     01h
        JNC      FAIL
        MVI     A,03
        OUT     CHKPT

; combo 4: J C=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        JNC      L4
        JMP     FAIL
L4:
        MVI     A,04
        OUT     CHKPT

; combo 5: J Z=1 sense=T -> taken
        MVI     A,00h
        ADI     00h
        JZ      L5
        JMP     FAIL
L5:
        MVI     A,05
        OUT     CHKPT

; combo 6: J Z=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        JZ      FAIL
        MVI     A,06
        OUT     CHKPT

; combo 7: J Z=1 sense=F -> not taken
        MVI     A,00h
        ADI     00h
        JNZ      FAIL
        MVI     A,07
        OUT     CHKPT

; combo 8: J Z=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        JNZ      L8
        JMP     FAIL
L8:
        MVI     A,08
        OUT     CHKPT

; combo 9: J S=1 sense=T -> taken
        MVI     A,80h
        ADI     00h
        JM      L9
        JMP     FAIL
L9:
        MVI     A,09
        OUT     CHKPT

; combo 10: J S=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        JM      FAIL
        MVI     A,10
        OUT     CHKPT

; combo 11: J S=1 sense=F -> not taken
        MVI     A,80h
        ADI     00h
        JP      FAIL
        MVI     A,11
        OUT     CHKPT

; combo 12: J S=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        JP      L12
        JMP     FAIL
L12:
        MVI     A,12
        OUT     CHKPT

; combo 13: J P=1 sense=T -> taken
        MVI     A,03h
        ADI     00h
        JPE      L13
        JMP     FAIL
L13:
        MVI     A,13
        OUT     CHKPT

; combo 14: J P=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        JPE      FAIL
        MVI     A,14
        OUT     CHKPT

; combo 15: J P=1 sense=F -> not taken
        MVI     A,03h
        ADI     00h
        JPO      FAIL
        MVI     A,15
        OUT     CHKPT

; combo 16: J P=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        JPO      L16
        JMP     FAIL
L16:
        MVI     A,16
        OUT     CHKPT

; combo 17: C C=1 sense=T -> taken
        MVI     A,0FFh
        ADI     01h
        CC      SUBR
        MVI     A,17
        OUT     CHKPT

; combo 18: C C=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CC      SUBR
        MVI     A,18
        OUT     CHKPT

; combo 19: C C=1 sense=F -> not taken
        MVI     A,0FFh
        ADI     01h
        CNC      SUBR
        MVI     A,19
        OUT     CHKPT

; combo 20: C C=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CNC      SUBR
        MVI     A,20
        OUT     CHKPT

; combo 21: C Z=1 sense=T -> taken
        MVI     A,00h
        ADI     00h
        CZ      SUBR
        MVI     A,21
        OUT     CHKPT

; combo 22: C Z=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CZ      SUBR
        MVI     A,22
        OUT     CHKPT

; combo 23: C Z=1 sense=F -> not taken
        MVI     A,00h
        ADI     00h
        CNZ      SUBR
        MVI     A,23
        OUT     CHKPT

; combo 24: C Z=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CNZ      SUBR
        MVI     A,24
        OUT     CHKPT

; combo 25: C S=1 sense=T -> taken
        MVI     A,80h
        ADI     00h
        CM      SUBR
        MVI     A,25
        OUT     CHKPT

; combo 26: C S=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CM      SUBR
        MVI     A,26
        OUT     CHKPT

; combo 27: C S=1 sense=F -> not taken
        MVI     A,80h
        ADI     00h
        CP      SUBR
        MVI     A,27
        OUT     CHKPT

; combo 28: C S=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CP      SUBR
        MVI     A,28
        OUT     CHKPT

; combo 29: C P=1 sense=T -> taken
        MVI     A,03h
        ADI     00h
        CPE      SUBR
        MVI     A,29
        OUT     CHKPT

; combo 30: C P=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CPE      SUBR
        MVI     A,30
        OUT     CHKPT

; combo 31: C P=1 sense=F -> not taken
        MVI     A,03h
        ADI     00h
        CPO      SUBR
        MVI     A,31
        OUT     CHKPT

; combo 32: C P=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CPO      SUBR
        MVI     A,32
        OUT     CHKPT

; combo 33: R C=1 sense=T -> taken
        MVI     A,0FFh
        ADI     01h
        CALL    H_RC
        MVI     A,33
        OUT     CHKPT

; combo 34: R C=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CALL    H_RC
        MVI     A,34
        OUT     CHKPT

; combo 35: R C=1 sense=F -> not taken
        MVI     A,0FFh
        ADI     01h
        CALL    H_RNC
        MVI     A,35
        OUT     CHKPT

; combo 36: R C=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CALL    H_RNC
        MVI     A,36
        OUT     CHKPT

; combo 37: R Z=1 sense=T -> taken
        MVI     A,00h
        ADI     00h
        CALL    H_RZ
        MVI     A,37
        OUT     CHKPT

; combo 38: R Z=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CALL    H_RZ
        MVI     A,38
        OUT     CHKPT

; combo 39: R Z=1 sense=F -> not taken
        MVI     A,00h
        ADI     00h
        CALL    H_RNZ
        MVI     A,39
        OUT     CHKPT

; combo 40: R Z=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CALL    H_RNZ
        MVI     A,40
        OUT     CHKPT

; combo 41: R S=1 sense=T -> taken
        MVI     A,80h
        ADI     00h
        CALL    H_RM
        MVI     A,41
        OUT     CHKPT

; combo 42: R S=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CALL    H_RM
        MVI     A,42
        OUT     CHKPT

; combo 43: R S=1 sense=F -> not taken
        MVI     A,80h
        ADI     00h
        CALL    H_RP
        MVI     A,43
        OUT     CHKPT

; combo 44: R S=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CALL    H_RP
        MVI     A,44
        OUT     CHKPT

; combo 45: R P=1 sense=T -> taken
        MVI     A,03h
        ADI     00h
        CALL    H_RPE
        MVI     A,45
        OUT     CHKPT

; combo 46: R P=0 sense=T -> not taken
        MVI     A,01h
        ADI     00h
        CALL    H_RPE
        MVI     A,46
        OUT     CHKPT

; combo 47: R P=1 sense=F -> not taken
        MVI     A,03h
        ADI     00h
        CALL    H_RPO
        MVI     A,47
        OUT     CHKPT

; combo 48: R P=0 sense=F -> taken
        MVI     A,01h
        ADI     00h
        CALL    H_RPO
        MVI     A,48
        OUT     CHKPT

        MVI     A,49
        OUT     CHKPT           ; final
        MVI     A,00h
        HLT

FAIL:
        MVI     A,0FEh
        OUT     CHKPT
        HLT

        end
