#!/usr/bin/env python3
"""Generate cond_matrix_test_as.asm + cond_matrix_expected.txt.

VPLAN XP-08 / ST-11 residual: all 48 conditional combos - {JMP,CAL,RET}
x {C,Z,S,P} x {test-true,test-false} x {flag=0,flag=1} - each with its
own checkpoint, plus the expected taken/not-taken STATE COUNT per
combo so the checker can pair counts with outcomes (DS72 p.45:
J/C 9 or 11, R 3 or 5).

One source of truth: this table emits both the program and the
expectation file the check script consumes.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# (flag, value) -> setter lines (only the tested flag must be exact)
SETTERS = {
    ("C", 1): ["MVI     A,0FFh", "ADI     01h"],
    ("C", 0): ["MVI     A,01h",  "ADI     00h"],
    ("Z", 1): ["MVI     A,00h",  "ADI     00h"],
    ("Z", 0): ["MVI     A,01h",  "ADI     00h"],
    ("S", 1): ["MVI     A,80h",  "ADI     00h"],
    ("S", 0): ["MVI     A,01h",  "ADI     00h"],
    ("P", 1): ["MVI     A,03h",  "ADI     00h"],
    ("P", 0): ["MVI     A,01h",  "ADI     00h"],
}

# 8080-syntax mnemonics per (flag, sense): sense 'T' = jump if flag set
JMNEM = {("C","T"):"JC", ("C","F"):"JNC", ("Z","T"):"JZ", ("Z","F"):"JNZ",
         ("S","T"):"JM", ("S","F"):"JP",  ("P","T"):"JPE",("P","F"):"JPO"}
CMNEM = {("C","T"):"CC", ("C","F"):"CNC", ("Z","T"):"CZ", ("Z","F"):"CNZ",
         ("S","T"):"CM", ("S","F"):"CP",  ("P","T"):"CPE",("P","F"):"CPO"}
RMNEM = {("C","T"):"RC", ("C","F"):"RNC", ("Z","T"):"RZ", ("Z","F"):"RNZ",
         ("S","T"):"RM", ("S","F"):"RP",  ("P","T"):"RPE",("P","F"):"RPO"}

combos = []          # (id, family, flag, sense, value, taken)
cid = 0
for family in ("J", "C", "R"):
    for flag in ("C", "Z", "S", "P"):
        for sense in ("T", "F"):
            for value in (1, 0):
                cid += 1
                taken = (value == 1) if sense == "T" else (value == 0)
                combos.append((cid, family, flag, sense, value, taken))

asm = []
a = asm.append
a("; GENERATED by gen_cond_matrix.py - do not edit by hand.")
a("; All 48 conditional combos (VPLAN XP-08); expectations in")
a("; cond_matrix_expected.txt consumed by check_cond_matrix_test.sh.")
a(";")
a("; D counts taken calls, E counts not-taken returns (helper falls")
a("; through the RXc). FAIL emits checkpoint 0xFE and halts.")
a("")
a("        cpu     8008new")
a("        page    0")
a("")
a("CHKPT   equ     31")
a("")
a("        org     0000h")
a("STARTUP:")
a("        MOV     A,A")
a("        MOV     A,A")
a("        JMP     MAIN")
a("")
a("SUBR:                           ; taken-call counter")
a("        INR     D")
a("        RET")
a("")
for (fl, sn), mn in RMNEM.items():
    a(f"H_{mn}:")
    a(f"        {mn}                      ; conditional return under test")
    a("        INR     E               ; not-taken path")
    a("        RET")
    a("")
a("        org     0200h")
a("MAIN:")
a("        MVI     D,00h")
a("        MVI     E,00h")
a("")
for cid, family, flag, sense, value, taken in combos:
    a(f"; combo {cid}: {family} {flag}{'=1' if value else '=0'} sense={sense}"
      f" -> {'taken' if taken else 'not taken'}")
    for line in SETTERS[(flag, value)]:
        a(f"        {line}")
    if family == "J":
        mn = JMNEM[(flag, sense)]
        if taken:
            a(f"        {mn}      L{cid}")
            a("        JMP     FAIL")
            a(f"L{cid}:")
        else:
            a(f"        {mn}      FAIL")
    elif family == "C":
        mn = CMNEM[(flag, sense)]
        a(f"        {mn}      SUBR")
    else:
        mn = RMNEM[(flag, sense)]
        a(f"        CALL    H_{mn}")
    a(f"        MVI     A,{cid:02d}")
    a("        OUT     CHKPT")
    a("")
a("        MVI     A,49")
a("        OUT     CHKPT           ; final")
a("        MVI     A,00h")
a("        HLT")
a("")
a("FAIL:")
a("        MVI     A,0FEh")
a("        OUT     CHKPT")
a("        HLT")
a("")
a("        end")

with open(os.path.join(HERE, "cond_matrix_test_as.asm"), "w") as f:
    f.write("\n".join(asm) + "\n")

# Expectations: id family flag sense value taken dD dE states
d = e = 0
with open(os.path.join(HERE, "cond_matrix_expected.txt"), "w") as f:
    f.write("# id family flag sense value taken D E states\n")
    for cid, family, flag, sense, value, taken in combos:
        if family == "C" and taken:
            d += 1
        if family == "R" and not taken:
            e += 1
        states = (11 if taken else 9) if family in ("J", "C") else (5 if taken else 3)
        f.write(f"{cid} {family} {flag} {sense} {value} {int(taken)} {d} {e} {states}\n")

print(f"generated {len(combos)} combos, final D={d} E={e}")
